### ISSUE TITLE
1.7.0 doesn't work with Umbraco 7.6.X

### ISSUE THREAD

**Issue by joshreid** [uComponents/nuPickers#175] opened 2017-07-02 02:48 UTC
The options are not available in the DataType configuration...

<img width="891" alt="screen shot 2017-07-02 at 2 34 01 pm" src="https://user-images.githubusercontent.com/167671/27766881-6e6a34fc-5f35-11e7-9f2a-40d8418bb8d4.png">

**Comment by rossdc02** [comment] 2017-08-31 11:53
Are there any plans to update to v1.7.6 in the near future? I am trying to sell Umbraco to our business and feel this is a pretty large gap.

**Comment by Hendy** [comment] 2017-09-06 13:27
Hi @joshreid I'm unable to reproduce this issue (it's working fine on a 7.6.4 install here). Closing, but can re-open if we can provide steps to reproduce it.

**Closed as completed by Hendy** 2017-09-06 13:27 UTC
