### ISSUE TITLE
Cant use SetValue on eventhandler

### ISSUE THREAD

**Issue by rasmusfjord** [uComponents/nuPickers#160] opened 2017-03-24 09:54 UTC
Hey I have a simple ExamineNupicker on a member, and I hook into the member Created event and saves the csv value as i would usally, but its just not being saved.

   private void MemberService_Created(IMemberService sender, NewEventArgs<IMember> e)
        {
          
            if (e.Alias == "skyIntraMember")
            {
                  string csv = "1000,1111"
            
                e.Entity.SetValue("underkategorier", csv);
                
            }
        }

Ive tried saving it to a textfield, works great, tried doing it in a template where i fetch an already saved member and set the value, this works fine but just not on the event. I tried building a complete picker object and saving that one still nothing. ¨

Running umbraco 7.5.9 and latest nupicker.

**Comment by Hendy** [comment] 2017-03-28 21:50
Hi @rasmusfjord would you be able to post the configuration details of your picker so I can try and recreate the issue here ?

**Comment by Hendy** [comment] 2017-04-06 08:58
Hi @rasmusfjord the Lucene picker should behave as the others, the only event that could change this data is the Relations Mapping event that will wipe the stored value (on Saved event) if using "Relations Only" (can you confirm that you are not using relations ?)

**Comment by rasmusfjord** [comment] 2017-04-06 08:59
Hey Hendy

Yeah i can confirm im not using relations, just saving as Csv. :) 

Med venlig hilsen
----
Rasmus Fjord

42407620

On 06-04-2017 10:58:43, Hendy Racher <notifications@github.com> wrote:
Hi @rasmusfjord [https://github.com/rasmusfjord] the Lucene picker should behave as the others, the only event that could change this data is the Relations Mapping event that will wipe the stored value (on Saved event) if using "Relations Only" (can you confirm that you are not using relations ?)

**Comment by Hendy** [comment] 2017-04-15 17:49
Hi @rasmusfjord, 

I can produce the same issue with the built in Textarea data-type, so can I ask which textfield property you could set correctly in the Created event ? I found setting the default comments textarea field on the member did work (but this seems to be treated differently, as it's a property called Comments on the member obj, rather than just within the Properties collection)

Stepping though the code indicated the MemberService.Saved event was called twice, and on the second call, both the Textarea and nuPicker property values were null, but no code in nuPickers had changed the value.

Going to close this as I don't think the issue is in nuPickers, but can re-open if there's more evidence.

Thanks,
Hendy

**Closed by Hendy** 2017-04-15 17:49 UTC
Labels: investigating
