### ISSUE TITLE
PickedKeys Count 0 when using Relations Only Save Format

### ISSUE THREAD

**Issue by s6admin** [uComponents/nuPickers#58] opened 2014-10-13 15:58 UTC
Hi all!

Love the nuPickers project – amazingly powerful and well structured, even for someone as slow as myself =)

I'm able to wire-up a bi-directional relationship between two published Documents and can render the PickedKeys value on the front-end without a problem. However, when I try to query the same data from a remote page (without using Model or CurrentPage) the PickedKeys Count is always 0.

I'm linking Products to Product Categories. So, on the Product View, this works perfectly:

```
    var productCategories = Model.Content.GetPropertyValue<Picker>("category");
    @productCategories.PickedKeys.Count() // Renders "3"
```

But retrieving the same product from a remote page (ie. the site Home page) doesn't work:

```
    IPublishedContent product = Umbraco.TypedContent(1234); // Product exists elsewhere in the Content tree
    var productCategories = product.GetPropertyValue<Picker>("category");
    @productCategories.PickedKeys.Count() // Renders "0"
```

Is this a limitation of nuPickers, Umbraco 7, or am I simply misunderstanding how to query the data in this type of situation?

Thank you!

**Comment by Hendy** [comment] 2015-02-14 22:34
Hi @s6admin, 
That shouldn't happen ! what's the save format, is it relations only ?
Thanks,
Hendy

**Comment by thalseth** [comment] 2015-05-12 14:48
I'm having the same issue. Did you manage to solve this @s6admin, @Hendy ?

**Comment by Hendy** [comment] 2015-05-12 14:51
Hi @thalseth is the save format relations only ?

**Comment by thalseth** [comment] 2015-05-12 14:57
Yes @Hendy

**Comment by thalseth** [comment] 2015-05-13 08:27
I'm really stuck with this issue @Hendy 
Is there anything i can do to help you in the process of fixing this?
Do you have any idea where to start looking?

Cheers

**Comment by Hendy** [comment] 2015-05-13 08:38
HI @thalseth I'd start by stepping though the [PickedKeys property](https://github.com/uComponents/nuPickers/blob/master/source/nuPickers/Picker.cs#L96) - just had a quick look, and the logic to get data from relations is in there, so perhaps it's a bug with the contextId value or 

    this.GetDataTypePreValue("saveFormat").Value == "relationsOnly" 

not being matched ?

**Comment by thalseth** [comment] 2015-05-13 11:11
Yes, it seems like we are out of context (contextId equals -1) @Hendy.

**Comment by Hendy** [comment] 2015-05-13 11:18
Thanks @thalseth, then the issue is likely to be in [in this line](https://github.com/uComponents/nuPickers/blob/master/source/nuPickers/PickerPropertyValueConverter.cs#L70)

Where are you calling it from ?

**Comment by thalseth** [comment] 2015-05-13 11:51
Yes i get this exception when debugging: 
Cannot return the IPublishedContent because the UmbracoHelper was constructed with an UmbracoContext and the current request is not a front-end request.

I'm instantiating my models in a UmbracoApiController using Ditto and a simple custom type converter.

Controller: https://gist.github.com/thalseth/e9e76544cd2e0a7c1f37 
TypeConverter: https://gist.github.com/thalseth/9c3045fb89ce923d76d0

Thanks for replying so fast @Hendy!

**Comment by Hendy** [comment] 2015-05-13 11:58
I can see a way of hacking your TypeConverter to create an instance of a Picker object supplying the appropriate parameters, but it'd be better to solve this issue within the nuPickers PropertyValueConverter.

I wonder if there's a way we can get the ID via another mechanism if the UmbracoHelper fails ?

**Comment by thalseth** [comment] 2015-05-13 12:44
I created [this](https://gist.github.com/thalseth/569372362348b9bfe96d) helper in another project.
Maybe there is something we can use here?

I guess i have to use this technique for now. Unless you want to tell me the hack? :angel:

**Comment by Hendy** [comment] 2015-05-14 06:18
Hi @thalseth my first thought of a workaround would be to construct the Picker obj, using contextId + propertyAlias in the TypeConverter (I'm guessing here), but I'll see if I can find another way of getting at the currentId in the PropertyValueConverter.

**Comment by Hendy** [comment] 2017-04-06 07:19
Hi @s6admin @thalseth sorry for the late reply, I'm guessing the issue is in the ProperyValueConverter where it [tries to calculate the context](https://github.com/uComponents/nuPickers/blob/master/source/nuPickers/PickerPropertyValueConverter.cs#L73) (by incorrectly trying to take the current context). I wonder if the PropertyValueConverter is able to obtain the context in another way ? (otherwise we would need to store the current id in the save value somehow)

**Comment by Hendy** [comment] 2017-04-07 16:26
Hi @s6admin @thalseth  unfortunately at the moment we can't get the [context in the PropertyValueConverter](https://our.umbraco.org/forum/developing-packages/85047-context-property-value-converters), so whilst this will for for the current node, what we can do is provide an extension method on IPublishedContent.GetPicker("propertyAlias") ?

**Comment by Hendy** [comment] 2017-04-15 16:00
Closing as workaround extension method on IPublihsedContent implemented: `.GetPicker("propertyAlias")`

Issue #163 covers the original issue and remains open

**Closed by Hendy** 2017-04-15 16:00 UTC
Labels: task
